### PR TITLE
Fill schools.txt with schools with schedules

### PR DESCRIPTION
**Pull request by wustep**
Added all schools with populated schedules.

quick script:
```
import glob
files = glob.glob("_sources/m3/rosters/*")

teams = [file.split("/")[3].split('.')[0][:-7] for file in files]
for team in sorted(teams):
    print(team)
```

Alternatively, all schools with rosters:
```
abilene-christian
air-force
akron
alabama
alabama-am
alabama-birmingham
alabama-state
albany-ny
alcorn-state
american
appalachian-state
arizona
arizona-state
arkansas
arkansas-little-rock
arkansas-pine-bluff
arkansas-state
army
auburn
austin-peay
ball-state
baylor
belmont
bethune-cookman
binghamton
boise-state
boston-college
boston-university
bowling-green-state
bradley
brigham-young
brown
bryant
bucknell
buffalo
butler
cal-poly
cal-state-bakersfield
cal-state-fullerton
cal-state-northridge
california
california-baptist
california-davis
california-irvine
california-riverside
california-santa-barbara
campbell
canisius
central-arkansas
central-connecticut-state
central-florida
central-michigan
charleston-southern
charlotte
chattanooga
chicago-state
cincinnati
citadel
clemson
cleveland-state
coastal-carolina
colgate
college-of-charleston
colorado
colorado-state
columbia
connecticut
coppin-state
cornell
creighton
dartmouth
davidson
dayton
delaware
delaware-state
denver
depaul
detroit-mercy
drake
drexel
duke
duquesne
east-carolina
east-tennessee-state
eastern-illinois
eastern-kentucky
eastern-michigan
eastern-washington
elon
evansville
fairfield
fairleigh-dickinson
florida
florida-am
florida-atlantic
florida-gulf-coast
florida-international
florida-state
fordham
fresno-state
furman
gardner-webb
george-mason
george-washington
georgetown
georgia
georgia-southern
georgia-state
georgia-tech
gonzaga
grambling
grand-canyon
green-bay
hampton
hartford
harvard
hawaii
high-point
hofstra
holy-cross
houston
houston-baptist
howard
idaho
idaho-state
illinois
illinois-chicago
illinois-state
incarnate-word
indiana
indiana-state
iona
iowa
iowa-state
ipfw
iupui
jackson-state
jacksonville
jacksonville-state
james-madison
kansas
kansas-state
kennesaw-state
kent-state
kentucky
la-salle
lafayette
lamar
lehigh
liberty
lipscomb
long-beach-state
long-island-university
longwood
louisiana-lafayette
louisiana-monroe
louisiana-state
louisiana-tech
louisville
loyola-il
loyola-marymount
loyola-md
maine
manhattan
marist
marquette
marshall
maryland
maryland-baltimore-county
maryland-eastern-shore
massachusetts
massachusetts-lowell
mcneese-state
memphis
mercer
miami-fl
miami-oh
michigan
michigan-state
middle-tennessee
milwaukee
minnesota
mississippi
mississippi-state
mississippi-valley-state
missouri
missouri-kansas-city
missouri-state
monmouth
montana
montana-state
morehead-state
morgan-state
mount-st-marys
murray-state
navy
nebraska
nebraska-omaha
nevada
nevada-las-vegas
new-hampshire
new-mexico
new-mexico-state
new-orleans
niagara
nicholls-state
njit
norfolk-state
north-alabama
north-carolina
north-carolina-asheville
north-carolina-at
north-carolina-central
north-carolina-greensboro
north-carolina-state
north-carolina-wilmington
north-dakota
north-dakota-state
north-florida
north-texas
northeastern
northern-arizona
northern-colorado
northern-illinois
northern-iowa
northern-kentucky
northwestern
northwestern-state
notre-dame
oakland
ohio
ohio-state
oklahoma
oklahoma-state
old-dominion
oral-roberts
oregon
oregon-state
pacific
penn-state
pennsylvania
pepperdine
pittsburgh
portland
portland-state
prairie-view
presbyterian
princeton
providence
purdue
quinnipiac
radford
rhode-island
rice
richmond
rider
robert-morris
rutgers
sacramento-state
sacred-heart
saint-francis-pa
saint-josephs
saint-louis
saint-marys-ca
saint-peters
sam-houston-state
samford
san-diego
san-diego-state
san-francisco
san-jose-state
santa-clara
savannah-state
seattle
seton-hall
siena
south-alabama
south-carolina
south-carolina-state
south-carolina-upstate
south-dakota
south-dakota-state
south-florida
southeast-missouri-state
southeastern-louisiana
southern
southern-california
southern-illinois
southern-illinois-edwardsville
southern-methodist
southern-mississippi
southern-utah
st-bonaventure
st-francis-ny
st-johns-ny
stanford
stephen-f-austin
stetson
stony-brook
syracuse
temple
tennessee
tennessee-martin
tennessee-state
tennessee-tech
texas
texas-am
texas-am-corpus-christi
texas-arlington
texas-christian
texas-el-paso
texas-pan-american
texas-san-antonio
texas-southern
texas-state
texas-tech
toledo
towson
troy
tulane
tulsa
ucla
utah
utah-state
utah-valley
valparaiso
vanderbilt
vermont
villanova
virginia
virginia-commonwealth
virginia-military-institute
virginia-tech
wagner
wake-forest
washington
washington-state
weber-state
west-virginia
western-carolina
western-illinois
western-kentucky
western-michigan
wichita-state
william-mary
winthrop
wisconsin
wofford
wright-state
wyoming
xavier
yale
youngstown-state
​```

### CODE REVIEW

**Comment by treyhakanson** [comment]
Can you close this and attempt to merge into `CSE5522` instead of `master`? Most of this repo is unrelated to the project so I plan on leaving it out of the project

**Comment by wustep** [comment]
yep!

PS - I'm working on a [programming lesson using your repo](https://github.com/wustep/programming/blob/master/IntroToPython/4-MarchMadness.ipynb) and needed a list of schools :)

**Comment by wustep** [comment]
Oh wait, my PR is unrelated to the project - the schools.txt file is empty and shouldn't be -- I can merge to `CSE5522` instead tho

**Comment by treyhakanson** [comment]
Yep just noticed that, reopenning and merging

**Pull request merged**
